### PR TITLE
feat(file_explorers): added support for `fern.vim`

### PR DESCRIPTION
**Pull request by wuelnerdotexe**
Hi! @andweeb - would you be so kind as to accept this small contribution :)

### CODE REVIEW

**Comment by wuelnerdotexe** [comment]
Oh my God, I didn't upload a missing comma, could you please add it? or you don't mind if I add another commit. Sorry !! 😣

**Comment by wuelnerdotexe** [comment]
I have added the missing comma \0/

**Comment by andweeb** [comment]
Apologies for the late follow-up, thanks again for the PR @wuelnerdotexe! LGTM!

**Comment by wuelnerdotexe** [comment]
@andweeb thanks to you for accepting \0/

**Pull request merged**
